create table category (id bigint not null, created_at datetime(6), update_at datetime(6), name varchar(255), primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table jt_instructor (specialization varchar(255), user_id bigint not null, primary key (user_id)) engine=InnoDB;
create table jt_mentor (avg_rating float(23) not null, number_of_session integer not null, user_id bigint not null, primary key (user_id)) engine=InnoDB;
create table jt_tas (avg_rating float(23) not null, number_of_call integer not null, user_id bigint not null, primary key (user_id)) engine=InnoDB;
create table ms_instructor (id bigint not null, email varchar(255), name varchar(255), password varchar(255), specialization varchar(255), primary key (id)) engine=InnoDB;
create table ms_mentor (id bigint not null, email varchar(255), name varchar(255), password varchar(255), avg_rating float(23) not null, number_of_session integer not null, primary key (id)) engine=InnoDB;
create table ms_tas (id bigint not null, email varchar(255), name varchar(255), password varchar(255), avg_rating float(23) not null, number_of_call integer not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, created_at datetime(6), update_at datetime(6), description varchar(255), image varchar(255), name varchar(255), price integer not null, category_id bigint, primary key (id)) engine=InnoDB;
create table product_seq (next_val bigint) engine=InnoDB;
insert into product_seq values ( 1 );
create table st_user (user_type integer not null, id bigint not null, email varchar(255), name varchar(255), password varchar(255), specialization varchar(255), avg_rating float(23), number_of_session integer, number_of_call integer, primary key (id)) engine=InnoDB;
create table tpc_instructor (id bigint not null, email varchar(255), name varchar(255), password varchar(255), specialization varchar(255), primary key (id)) engine=InnoDB;
create table tpc_mentor (id bigint not null, email varchar(255), name varchar(255), password varchar(255), avg_rating float(23) not null, number_of_session integer not null, primary key (id)) engine=InnoDB;
create table tpc_tas (id bigint not null, email varchar(255), name varchar(255), password varchar(255), avg_rating float(23) not null, number_of_call integer not null, primary key (id)) engine=InnoDB;
create table tpc_user (id bigint not null, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
create table user (id bigint not null, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table jt_instructor add constraint FKkpodhyfi5h4cacgalkk8d8ggk foreign key (user_id) references user (id);
alter table jt_mentor add constraint FKteiaxfabydeyp9if885u9nnfv foreign key (user_id) references user (id);
alter table jt_tas add constraint FK1d7vouqmklcvuxjyygly6n88d foreign key (user_id) references user (id);
alter table product add constraint FK1mtsbur82frn64de7balymq9s foreign key (category_id) references category (id);